version: '3.9'

services:

  hub:
    image: selenium/hub:4.21.0
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.21.0
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

#  tests:
#    build: .
#    depends_on:
#      - hub
#      - chrome
#    environment:
#      - HUB_HOST=hub
#    entrypoint: ["mvn"]
#    command: ["clean", "test"]
