version: '3.9'

services:

  selenium-hub:
    image: selenium/hub:4.21.0
    network_mode: "host"  # 👈 makes localhost:4444 work from the host
    ports:
      - "4442:4442"  # For router to session queue/distributor
      - "4443:4443"  # For router to node communication
      - "4444:4444"  # WebDriver client entry point
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300

  chrome:
    image: selenium/node-chrome:4.21.0
    depends_on:
      - selenium-hub
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.21.0
    depends_on:
      - selenium-hub
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

#  allure-server:
#    image: fescobar/allure-docker-service
#    container_name: allure-server
#    ports:
#      - "5050:5050"
#    environment:
#      CHECK_RESULTS_EVERY_SECONDS: 5
#      KEEP_HISTORY: 1
#    volumes:
#      - ./allure-results:/app/allure-results
#      - ./allure-report:/app/allure-report

#  allure-ui:
#    image: fescobar/allure-docker-ui
#    container_name: allure-ui
#    ports:
#      - "5252:5252"
#    environment:
#      - ALLURE_DOCKER_PUBLIC_API_URL=http://localhost:5050

#  selenium-tests:
#    build: .
#    depends_on:
#      - selenium-hub
#      - chrome-node
#      - firefox-node
#    volumes:
#      - ./allure-results:/app/allure-results
#    environment:
#      - HUB_HOST=selenium-hub
#    entrypoint: ["mvn"]
#    command: ["clean", "test"]
